"""Adding image to game table

Revision ID: 346c12d1451d
Revises: 3fe6cf89550d
Create Date: 2024-03-19 19:51:52.249029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346c12d1451d'
down_revision = '3fe6cf89550d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
